/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as QuotaRouteImport } from './routes/quota'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ModelRouteImport } from './routes/model'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as BenchRouteImport } from './routes/bench'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MNameRouteImport } from './routes/m.$name'
import { Route as KeysKeyRouteImport } from './routes/keys_.$key'
import { Route as BenchRunRouteImport } from './routes/bench_.run'
import { Route as BenchProbeRouteImport } from './routes/bench_.probe'
import { Route as BenchModelRouteImport } from './routes/bench_.model'
import { Route as MNameActivityRouteImport } from './routes/m.$name.activity'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotaRoute = QuotaRouteImport.update({
  id: '/quota',
  path: '/quota',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRoute = BenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MNameRoute = MNameRouteImport.update({
  id: '/m/$name',
  path: '/m/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysKeyRoute = KeysKeyRouteImport.update({
  id: '/keys_/$key',
  path: '/keys/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRunRoute = BenchRunRouteImport.update({
  id: '/bench_/run',
  path: '/bench/run',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchProbeRoute = BenchProbeRouteImport.update({
  id: '/bench_/probe',
  path: '/bench/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchModelRoute = BenchModelRouteImport.update({
  id: '/bench_/model',
  path: '/bench/model',
  getParentRoute: () => rootRouteImport,
} as any)
const MNameActivityRoute = MNameActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => MNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/bench': typeof BenchRoute
  '/config': typeof ConfigRoute
  '/groups': typeof GroupsRoute
  '/keys': typeof KeysRoute
  '/model': typeof ModelRoute
  '/providers': typeof ProvidersRoute
  '/quota': typeof QuotaRoute
  '/usage': typeof UsageRoute
  '/bench/model': typeof BenchModelRoute
  '/bench/probe': typeof BenchProbeRoute
  '/bench/run': typeof BenchRunRoute
  '/keys/$key': typeof KeysKeyRoute
  '/m/$name': typeof MNameRouteWithChildren
  '/m/$name/activity': typeof MNameActivityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/bench': typeof BenchRoute
  '/config': typeof ConfigRoute
  '/groups': typeof GroupsRoute
  '/keys': typeof KeysRoute
  '/model': typeof ModelRoute
  '/providers': typeof ProvidersRoute
  '/quota': typeof QuotaRoute
  '/usage': typeof UsageRoute
  '/bench/model': typeof BenchModelRoute
  '/bench/probe': typeof BenchProbeRoute
  '/bench/run': typeof BenchRunRoute
  '/keys/$key': typeof KeysKeyRoute
  '/m/$name': typeof MNameRouteWithChildren
  '/m/$name/activity': typeof MNameActivityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/bench': typeof BenchRoute
  '/config': typeof ConfigRoute
  '/groups': typeof GroupsRoute
  '/keys': typeof KeysRoute
  '/model': typeof ModelRoute
  '/providers': typeof ProvidersRoute
  '/quota': typeof QuotaRoute
  '/usage': typeof UsageRoute
  '/bench_/model': typeof BenchModelRoute
  '/bench_/probe': typeof BenchProbeRoute
  '/bench_/run': typeof BenchRunRoute
  '/keys_/$key': typeof KeysKeyRoute
  '/m/$name': typeof MNameRouteWithChildren
  '/m/$name/activity': typeof MNameActivityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/bench'
    | '/config'
    | '/groups'
    | '/keys'
    | '/model'
    | '/providers'
    | '/quota'
    | '/usage'
    | '/bench/model'
    | '/bench/probe'
    | '/bench/run'
    | '/keys/$key'
    | '/m/$name'
    | '/m/$name/activity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/bench'
    | '/config'
    | '/groups'
    | '/keys'
    | '/model'
    | '/providers'
    | '/quota'
    | '/usage'
    | '/bench/model'
    | '/bench/probe'
    | '/bench/run'
    | '/keys/$key'
    | '/m/$name'
    | '/m/$name/activity'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/bench'
    | '/config'
    | '/groups'
    | '/keys'
    | '/model'
    | '/providers'
    | '/quota'
    | '/usage'
    | '/bench_/model'
    | '/bench_/probe'
    | '/bench_/run'
    | '/keys_/$key'
    | '/m/$name'
    | '/m/$name/activity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  BenchRoute: typeof BenchRoute
  ConfigRoute: typeof ConfigRoute
  GroupsRoute: typeof GroupsRoute
  KeysRoute: typeof KeysRoute
  ModelRoute: typeof ModelRoute
  ProvidersRoute: typeof ProvidersRoute
  QuotaRoute: typeof QuotaRoute
  UsageRoute: typeof UsageRoute
  BenchModelRoute: typeof BenchModelRoute
  BenchProbeRoute: typeof BenchProbeRoute
  BenchRunRoute: typeof BenchRunRoute
  KeysKeyRoute: typeof KeysKeyRoute
  MNameRoute: typeof MNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quota': {
      id: '/quota'
      path: '/quota'
      fullPath: '/quota'
      preLoaderRoute: typeof QuotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$name': {
      id: '/m/$name'
      path: '/m/$name'
      fullPath: '/m/$name'
      preLoaderRoute: typeof MNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys_/$key': {
      id: '/keys_/$key'
      path: '/keys/$key'
      fullPath: '/keys/$key'
      preLoaderRoute: typeof KeysKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench_/run': {
      id: '/bench_/run'
      path: '/bench/run'
      fullPath: '/bench/run'
      preLoaderRoute: typeof BenchRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench_/probe': {
      id: '/bench_/probe'
      path: '/bench/probe'
      fullPath: '/bench/probe'
      preLoaderRoute: typeof BenchProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench_/model': {
      id: '/bench_/model'
      path: '/bench/model'
      fullPath: '/bench/model'
      preLoaderRoute: typeof BenchModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$name/activity': {
      id: '/m/$name/activity'
      path: '/activity'
      fullPath: '/m/$name/activity'
      preLoaderRoute: typeof MNameActivityRouteImport
      parentRoute: typeof MNameRoute
    }
  }
}

interface MNameRouteChildren {
  MNameActivityRoute: typeof MNameActivityRoute
}

const MNameRouteChildren: MNameRouteChildren = {
  MNameActivityRoute: MNameActivityRoute,
}

const MNameRouteWithChildren = MNameRoute._addFileChildren(MNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  BenchRoute: BenchRoute,
  ConfigRoute: ConfigRoute,
  GroupsRoute: GroupsRoute,
  KeysRoute: KeysRoute,
  ModelRoute: ModelRoute,
  ProvidersRoute: ProvidersRoute,
  QuotaRoute: QuotaRoute,
  UsageRoute: UsageRoute,
  BenchModelRoute: BenchModelRoute,
  BenchProbeRoute: BenchProbeRoute,
  BenchRunRoute: BenchRunRoute,
  KeysKeyRoute: KeysKeyRoute,
  MNameRoute: MNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
