// Package service installs corrallm as a systemd user service.
//
// corrallm was started by hand — a 228-line launcher in a neighbouring repo
// (ml-kit's bin/run) that built the binary, validated the config, wrapped the
// process in a transient systemd scope for its OOM policy, and swept the port.
// Nothing started it at boot, so a reboot left the gateway and every model down
// until a person noticed, and the knowledge of how to start it correctly lived
// outside the thing being started.
//
// It belongs here: corrallm already knows its own config path, home, port and
// shutdown semantics, and it is the only thing that can validate a config before
// swapping onto it. The one job the launcher had that does NOT move is building
// the binary — a service cannot build itself. That is `go install`, then
// `corrallm service restart`.
package service

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DefaultName is the unit name (without the .service suffix).
const DefaultName = "corrallm"

// Unit describes the service to render.
type Unit struct {
	Name        string   // unit name without .service
	Exec        string   // absolute path to the corrallm binary
	Args        []string // arguments to `serve`
	ConfigPath  string   // validated before start when set
	WorkingDir  string   // resolved from the config's directory when empty
	Env         []string // KEY=VALUE lines
	Description string
}

// UnitFileName is the file this unit installs as.
func (u Unit) UnitFileName() string {
	name := u.Name
	if name == "" {
		name = DefaultName
	}
	return name + ".service"
}

// UserUnitDir is where systemd reads per-user units from.
func UserUnitDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "systemd", "user"), nil
}

// quote renders one argument for a systemd Exec line.
//
// systemd does its own unquoting, so an argument containing a space (a config
// path under "Application Support", a reason string) must be quoted or it
// silently becomes two arguments.
func quote(s string) string {
	if s != "" && !strings.ContainsAny(s, " \t\"'\\$%") {
		return s
	}
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, `%`, `%%`)
	return `"` + r.Replace(s) + `"`
}

func execLine(exec string, args ...string) string {
	parts := make([]string, 0, len(args)+1)
	parts = append(parts, quote(exec))
	for _, a := range args {
		parts = append(parts, quote(a))
	}
	return strings.Join(parts, " ")
}

// Render produces the unit file.
//
// The properties here are not decoration; each one replaces something the shell
// launcher did, and the comments say which, because the next person to touch
// this will otherwise "clean up" a line that is load-bearing.
func (u Unit) Render() string {
	desc := u.Description
	if desc == "" {
		desc = "corrallm — OpenAI-compatible LLM gateway, lifecycle manager and scheduler"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `corrallm service install`. Edits are overwritten on reinstall.\n")
	fmt.Fprintf(&b, "[Unit]\nDescription=%s\nAfter=default.target\n\n", desc)
	b.WriteString("[Service]\nType=simple\n")

	if u.ConfigPath != "" {
		// Validate BEFORE the old process is replaced. `serve` frees the listen
		// port before it validates, so a bad config used to take the gateway
		// down rather than fail safe — a lane naming a deleted model exited at
		// startup with :8111 already released and the edge served 503 until
		// someone noticed. A failing ExecStartPre means the unit does not start
		// and, on a restart, systemd reports the failure with the old state
		// already gone — so pair this with `corrallm service restart`, which
		// validates before it stops anything.
		fmt.Fprintf(&b, "ExecStartPre=%s\n", execLine(u.Exec, "validate", "--config", u.ConfigPath))
	}
	fmt.Fprintf(&b, "ExecStart=%s\n", execLine(u.Exec, append([]string{"serve"}, u.Args...)...))

	if u.WorkingDir != "" {
		fmt.Fprintf(&b, "WorkingDirectory=%s\n", u.WorkingDir)
	}
	// Environment, not flags: some settings have no flag at all. The listen
	// address is the one that bites — `serve` reads ADDR from the environment,
	// and passing --addr exits 1 with "unknown flag". Under Restart=on-failure
	// that is not a failed start, it is a crash loop.
	for _, e := range u.Env {
		fmt.Fprintf(&b, "Environment=%s\n", e)
	}
	b.WriteString(`
# A backend OOM must not take the gateway with it. A diarize request once drove
# an extension to 119G anon-rss and triggered a global OOM; without this the
# kernel's choice of victim can be corrallm itself, and every model goes down
# with the process that knows how to restart them.
OOMPolicy=continue

# SIGTERM the main process ONLY, and let corrallm reap its own children: it
# drains in-flight requests, unloads backends and waits for VRAM to be released.
# The default (control-group) would signal every backend simultaneously, turning
# a graceful drain into a stampede. Backends spawned into their own transient
# scopes are outside this cgroup anyway and are reaped by corrallm regardless.
KillMode=mixed

# A drain waits for in-flight work, and a long transcription can hold it open.
# Too short here converts a graceful shutdown into a SIGKILL that strands VRAM.
TimeoutStopSec=90

Restart=on-failure
RestartSec=2

[Install]
WantedBy=default.target
`)
	return b.String()
}

// Install writes the unit into dir, creating it if needed, and reports the path.
func (u Unit) Install(dir string) (string, error) {
	if u.Exec == "" {
		return "", fmt.Errorf("no executable path for the unit")
	}
	if !filepath.IsAbs(u.Exec) {
		return "", fmt.Errorf("executable %q must be an absolute path: systemd does not search $PATH", u.Exec)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	p := filepath.Join(dir, u.UnitFileName())
	if err := os.WriteFile(p, []byte(u.Render()), 0o644); err != nil {
		return "", err
	}
	return p, nil
}
